id: AAF282AA7
title: 'The Sound of the Divine Drum: Advice at a Time of Victory'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:56:37.991156
  last_modified_at: 2022-03-01 05:56:37.991159
