id: AAF282AA7
title: 'Divine Music: Words of Encouragement for the Authentic Path'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:56:37.984147
  last_modified_at: 2022-03-01 05:56:37.984150
