id: AAF282AA7
title: 'Ḍākinī’s Delight: A Song of the Feast'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:56:37.996220
  last_modified_at: 2022-03-01 05:56:37.996223
