id: AAF282AA7
title: 'A Yogi’s Song of Happiness: The Melody that Brings Universal Auspiciousness
  and Fulfilment'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:56:37.980539
  last_modified_at: 2022-03-01 05:56:37.980569
