id: AAF282AA7
title: A Song of Prayer to Jamyang Loter Wangpo
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:56:37.975105
  last_modified_at: 2022-03-01 05:56:37.975110
