id: AAF282AA7
title: Song of the Feast (Tsok Lu)
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:56:37.987451
  last_modified_at: 2022-03-01 05:56:37.987454
