id: AAF282AA7
title: 'The Spontaneous Sound of Uncontrived Song: A Lament Recalling the Great Guru
  of Oḍḍiyāna'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:56:37.992727
  last_modified_at: 2022-03-01 05:56:37.992730
