id: AAF282AA7
title: Upon Arriving at Yangleshö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 05:56:37.994727
  last_modified_at: 2022-03-01 05:56:37.994731
